branchName: 'issue-${issue.number}-${issue.title[0,32]}'
gitReplaceChars: '/<>'
autoLinkIssue: true
openDraftPR: true
prSkipCI: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
conventionalPrTitles: true
conventionalLabels:
  fix:
    bug: '🐛'
    dependencies: '⬆️'
    security: '🔒'
  feat:
    enhancement: '✨'
    new-stuff: '🚀'
  build:
    build: '🔧'
  chore:
    chore: '♻️'
  ci:
    ci: '👷'
  docs:
    documentation: '📝'
  style:
    style: '💎'
  refactor:
    refactor: '♻️'
  perf:
    performance: '⚡️'
  test:
    test: '✅'
  breaking:
    breaking-change: '💥'
    breaking change: '💥'
